version: 2
updates:
  - package-ecosystem: npm
    directory: /code
    schedule:
      interval: weekly
      day: monday
      time: "10:00"
      timezone: America/Chicago
    open-pull-requests-limit: 1
    labels:
      - dependencies
      - security

  - package-ecosystem: composer
    directory: /code
    schedule:
      interval: weekly
      day: monday
      time: "10:15"
      timezone: America/Chicago
    open-pull-requests-limit: 1
    labels:
      - dependencies
      - security

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "10:30"
      timezone: America/Chicago
    open-pull-requests-limit: 1
    labels:
      - dependencies
      - ci
